package controllers;

public enum Events {
    INITIAL_PANEL_ACTIONS, ADD_GRAMMAR, EXIT, ADD_VARIABLE, ADD_SYMBOL, ADD_PRODUCTION ,ADD_GRAMMAR_ACTIONS,
    CREATE_GRAMMAR, LANGUAGE_PANEL_ACTIONS , CHECK_WORD, NEW_GRAMMAR
}
